
export const CardPhoto = [
    {
      img: '/Card/Hearthstone.webp',
        title: 'Hearthstone',
        description: 'Hearthstone is set in the Warcraft universe, where players take on the roles of iconic heroes and characters from the franchise, battling opponents by playing cards that represent minions, spells, and weapons. The game is mechanics are turn-based, and players must use strategy, resource management, and careful deck-building to outsmart their opponents.',
        description1: 'The game is known for its highly polished design, with vibrant, detailed art, unique sound effects, and a sense of humor that reflects Blizzard is signature style. Matches typically last 10-15 minutes, making Hearthstone fast-paced compared to other card games, and its accessibility has drawn millions of players worldwide.',
        description2: 'Over the years, Hearthstone has expanded with numerous expansions, single-player content, and regular balance updates, ensuring that the meta-game remains fresh and competitive.',
        play: 'Basic Game Mechanics:Mana: Players start each match with 1 mana crystal, gaining one more each turn, up to a maximum of 10. Mana is used to play cards, and each card has a mana cost.',
        play1: 'Cards: The cards in Hearthstone are divided into three main categories:Minions: Creatures that can attack your opponent and defend you. Each minion has an attack and health value.',
        play2: 'Classes and Heroes :Players can choose from one of 11 classes, each based on a character from Warcraft lore, such as Jaina Proudmoore (Mage), Thrall (Shaman), and Anduin Wrynn (Priest). Each class has unique class-specific cards and a hero power that fits their playstyle.',
        fileSize: '498 MB',
        version: '30.4.206605',
        time: 'Sep 3, 2024',
        Appto: 'https://apps.apple.com/us/app/hearthstone/id625257520',
        Playto: 'https://play.google.com/store/apps/details?id=com.blizzard.wtcg.hearthstone'
    },
    {
        img: '/Card/Yu-Gi-Oh!DuelLinks.webp',
          title: 'Yu-Gi-Oh! Duel Links',
          description: 'Yu-Gi-Oh! Duel Links takes place in a virtual world where players can engage in card duels with characters from the Yu-Gi-Oh! anime series. The game includes iconic characters like Yugi Muto, Seto Kaiba, Joey Wheeler, and many more from various eras of Yu-Gi-Oh!, including GX, 5D’s, and ZEXAL. Players collect cards, build decks, and battle against other duelists in both single-player and online PvP duels.',
          description1: 'The core gameplay is centered around using a deck of monsters, spells, and trap cards to reduce your opponent is life points to zero.',
          description2: 'The game uses the Speed Duel format, which simplifies some of the more complex aspects of traditional Yu-Gi-Oh! gameplay, allowing for quicker and more dynamic duels. Players use 20-30 card decks (as opposed to the traditional 40-60) and play on a smaller game board, with three monster zones and three spell/trap zones instead of the standard five. Life points are also reduced to 4,000, making each duel more fast-paced.',
          play: 'Gameplay Overview:Players can Normal Summon (once per turn), Tribute Summon (sacrificing weaker monsters to summon stronger ones), or Special Summon powerful monsters like Fusion, Synchro, or Xyz monsters depending on their deck strategy. ',
          play1: 'Spell and Trap Cards:Spell Cards: These cards can be activated during your turn to provide effects such as destroying enemy monsters, drawing more cards, or increasing the power of your monsters. Some spells are continuous and remain on the field, while others are one-time effects.',
          play2: 'Speed Duels:The Duel Links format is designed to create shorter, more intense matches. The game uses smaller decks (20-30 cards) and a smaller field (three monster zones and three spell/trap zones). ',
          fileSize: '98 MB',
          version: '8.11.0',
          time: 'Aug 19, 2024',
          Appto: 'https://apps.apple.com/us/app/yu-gi-oh-duel-links/id1068378177',
          Playto: 'https://play.google.com/store/apps/details?id=jp.konami.duellinks'
      },    {
        img: '/Card/LegendsofRuneterra.webp',
          title: 'Legends of Runeterra',
          description: 'Legends of Runeterra is a strategic card game that focuses on both tactical gameplay and building a collection of cards from a diverse set of champions and regions within the League of Legends universe. Unlike traditional card games, it introduces mechanics that encourage interaction between players, such as attacking and blocking phases that occur during the opponent is turn.',
          description1: 'The game features a rich array of champions, spells, and cards representing various factions and characters from the League of Legends lore. The strategic depth comes from building a deck that can handle different situations, leveraging synergies between cards, and adapting to the evolving tactics of your opponent.',
          description2: 'It combines strategic card play with the depth of the League of Legends lore, offering a unique and engaging experience for fans of both the card game and the MOBA.',
          play: 'Basic Game Mechanics:Deck Building: Players build a deck of 40 cards, selecting from a wide range of champions, spells, and followers. Decks are built around specific regions, each offering unique cards and abilities. Players can combine cards from up to two different regions. ',
          play1: 'Champions and Followers:Champions: Each deck includes powerful champion cards that have unique abilities and can level up during the game. Champions often have special effects or transformations that can turn the tide of the match. For example, Jinx evolves from a relatively weak card into a powerful one with explosive abilities.',
          play2: 'Spells:Fast Spells: Can be played at any time during your turn or your opponent is turn, allowing for flexible responses and interactions. ',
          fileSize: '238 MB',
          version: '05.09.032',
          time: 'Sep 5, 2024',
          Appto: 'https://apps.apple.com/us/app/legends-of-runeterra/id1480617557',
          Playto: 'https://play.google.com/store/apps/details?id=com.riotgames.legendsofruneterra'
      },    {
        img: '/Card/uno.webp',
          title: 'UNO!™',
          description: 'UNO!™ is a game where players try to be the first to get rid of all their cards by matching them to the card on the discard pile based on color or number. The game is designed for 2 to 10 players and involves strategic play and a bit of luck. It’s suitable for all ages, making it a popular choice for casual game nights and social gatherings.',
          description1: 'UNO!™ is a classic and widely recognized card game created by Merle Robbins and first published by Mattel in 1971. The game is known for its simple rules, fast-paced gameplay, and the fun it brings to family and friends. The digital version, UNO!™, is available on various platforms, including mobile devices and gaming consoles, allowing players to enjoy the game online or offline with friends and family.',
          description2: 'The digital version of UNO!™ retains the core mechanics of the original card game while introducing new features and modes to enhance the experience. Players can enjoy the classic game as well as various themed editions and special rules in the digital format.',
          play: 'The main objective of UNO!™ is to be the first player to score 500 points. Players earn points by getting rid of all their cards in each round and accumulating the point values of the cards remaining in their opponents hands.',
          play1: 'Players take turns matching a card from their hand to the card on the discard pile by either color or number. For example, if the discard pile has a red 7, a player can place any red card or any card with a 7 on top of it.',
          play2: 'If a player cannot match the discard pile, they must draw a card from the draw pile. If the drawn card can be played, the player may do so; otherwise, the turn passes to the next player. ',
          fileSize: '461 MB',
          version: '1.13.4641',
          time: 'Aug 22, 2024',
          Appto: 'https://apps.apple.com/us/app/uno/id1344700142',
          Playto: 'https://play.google.com/store/apps/details?id=com.matteljv.uno '
      },    {
        img: '/Card/TheGatheringArena.webp',
          title: 'Magic: The Gathering Arena',
          description: 'Magic: The Gathering Arena (MTG Arena) is a digital adaptation of the popular trading card game Magic: The Gathering (MTG), developed and published by Wizards of the Coast. Launched in 2018, MTG Arena brings the rich strategic depth and expansive lore of the physical card game to a digital format, making it accessible for players to enjoy on PC and mobile devices.',
          description1: 'Magic: The Gathering Arena captures the essence of the original Magic: The Gathering card game, with a streamlined interface and features designed to enhance the digital play experience. The game retains the complex strategies and vast card pool of MTG while offering modern conveniences and regular updates. Players can build decks, participate in various game modes, and compete in events, all within a visually engaging and interactive digital environment.',
          description2: 'The game is known for its strategic depth, where players use a deck of cards to cast spells, summon creatures, and utilize powerful abilities to defeat their opponents. MTG Arena includes a variety of formats, from casual play to competitive tournaments, catering to both new players and seasoned veterans of the card game.',
          play: 'Mana: The game uses a mana system, where players tap land cards to generate mana, which is used to cast spells and summon creatures. Mana comes in five colors (white, blue, black, red, and green), and deck-building strategies often focus on balancing these colors. ',
          play1: 'Creatures: These cards are summoned to the battlefield to attack opponents or defend against attacks. Creatures have attack (power) and defense (toughness) values and may have additional abilities or effects.',
          play2: 'Building a Deck: Players create decks by selecting cards that work well together, focusing on synergy and strategy. Decks typically include a mix of creatures, spells, and lands that complement each other and support the player’s overall strategy. ',
          fileSize: '1,020 MB',
          version: '2024.40.30.2906',
          time: 'Sep 12, 2024',
          Appto: 'https://apps.apple.com/us/app/magic-the-gathering-arena/id1496227521',
          Playto: 'https://play.google.com/store/apps/details?id=com.wizards.mtga'
      },    {
        img: '/Card/ClashRoyale.webp',
          title: 'Clash Royale',
          description: 'Clash Royale is a popular mobile strategy game developed and published by Supercell. Released in March 2016, it combines elements from collectible card games, tower defense, and multiplayer online battle arenas (MOBAs) into a unique and engaging real-time strategy experience. The game has been praised for its addictive gameplay, strategic depth, and competitive balance.',
          description1: 'Clash Royale is set in the same universe as Supercell’s Clash of Clans, featuring familiar characters and a similar visual style. In the game, players collect and upgrade cards representing troops, spells, and buildings, which they use to battle opponents in real-time, multiplayer matches. The objective is to destroy the enemy is towers while defending your own, with the ultimate goal of winning by taking down the opponent’s King Tower.',
          description2: 'The game features various arenas and modes, where players can participate in 1v1 battles, challenge matches, and special events. It also includes a robust progression system, allowing players to level up their cards and unlock new content as they advance through the game.',
          play: ' Deck Building: Players build a deck of 8 cards, choosing from a collection of troops, spells, and buildings. Each card has a unique cost, ability, and role in battle. Decks are customized to suit different strategies and playstyles.',
          play1: 'Troops: These are units that can be deployed onto the battlefield to attack enemy troops and buildings. Troops come in various forms, including melee fighters, ranged attackers, and flying units.',
          play2: 'Trophies: Trophies are earned by winning battles and are used to determine a player’s rank and arena. Losing battles results in a loss of trophies, so maintaining a winning streak is important for advancement. ',
          fileSize: '699 MB',
          version: '70288038',
          time: 'Aug 19, 2024',
          Appto: 'https://apps.apple.com/us/app/clash-royale/id1053012308',
          Playto: 'https://play.google.com/store/apps/details?id=com.supercell.clashroyale'
      },    {
        img: '/Card/TheWitcherCardGame.webp',
          title: 'GWENT: The Witcher Card Game',
          description: 'GWENT: The Witcher Card Game is a digital collectible card game developed and published by CD Projekt Red, set in the universe of The Witcher series. Released in 2018, GWENT is based on the popular card game featured within The Witcher 3: Wild Hunt, and it builds on that foundation with a unique gameplay experience and expanded lore.',
          description1: 'GWENT is a card game that combines strategic deck-building with tactical gameplay. It features factions and characters from The Witcher universe, with each faction having its own distinct playstyle and abilities. The game is known for its deep strategic elements, including card synergies, bluffing, and strategic management of resources.',
          description2: 'The objective of GWENT is to win two out of three rounds by playing cards to achieve the highest point total on the battlefield. Players must carefully manage their cards and strategies to outsmart their opponents and secure victory.',
          play: 'Deck Building: Players build a deck of 25 cards, selecting from various factions and card types. Each deck includes a leader card with a unique ability that can be used once per game. Decks are built around synergies between cards and specific strategies. ',
          play1: 'Units: These cards represent characters or creatures that are played on the battlefield and contribute to the player is point total. Units can have various abilities and effects, such as dealing damage, boosting other units, or generating resources.',
          play2: 'Rounds and Scoring: Each round involves placing cards on the battlefield to achieve the highest point total. Points are accumulated based on the strength of units and effects on the battlefield. The round ends when both players pass their turns.',
          fileSize: '3 GB',
          version: '11.10.9',
          time: 'Dec 20, 2023',
          Appto: 'https://apps.apple.com/us/app/gwent-the-witcher-card-game/id1466943149',
          Playto: 'https://play.google.com/store/apps/details?id=com.cdprojektred.gwent '
      },    {
        img: '/Card/CardThief.webp',
          title: 'Card Thief',
          description: 'Card Thief is a mobile stealth card game developed by Arnold Rauers, also known as Tinytouchtales, and released in 2017. The game combines elements of card-based mechanics with tactical stealth gameplay, offering a unique and innovative experience. Set in a dark and atmospheric world, Card Thief tasks players with completing heists while managing resources and avoiding detection.',
          description1: 'In Card Thief, you play as a sneaky rogue navigating through a deck of cards that represent various elements of a heist. The goal is to steal treasure, extinguish torches, and evade guards, all while strategically managing your movement and resources. The game is a hybrid of solitaire-like mechanics and stealth gameplay, where each card interaction represents a move in the heist.',
          description2: 'The board is laid out in a 3x3 grid of cards, where the thief moves from one card to another, interacting with obstacles, guards, and loot. The player must carefully plan each move to remain undetected, gather treasure, and escape successfully before the cards run out.',
          play: 'The Grid: The game is played on a 3x3 grid of cards, with the thief starting in a random position. Each card on the grid represents an object, character, or obstacle that impacts your heist in some way. ',
          play1: 'Treasure Cards: These are the primary target in each heist. Collecting treasure increases your score, but picking up treasure also reduces your stealth points, making it riskier to continue the heist.',
          play2: 'Pathing: Each turn, you can draw a path from your current position to one or more adjacent cards. You must consider the cost in stealth points for each card interaction, as some cards require more stealth to pass. ',
          fileSize: '93 MB',
          version: '1.3.8',
          time: 'Jan 8, 2024',
          Appto: 'https://apps.apple.com/us/app/card-thief/id1186226470',
          Playto: 'https://play.google.com/store/apps/details?id=com.tinytouchtales.cardthief'
      },    {
        img: '/Card/pokemon.webp',
          title: 'Pokémon TCG Live',
          description: 'Pokémon TCG Live is a digital version of the beloved Pokémon Trading Card Game (TCG), developed by The Pokémon Company International. It’s designed for players to experience the traditional TCG on digital platforms, offering a streamlined, accessible way to build decks, compete in matches, and engage with the vast Pokémon TCG universe. Released in open beta in late 2021, it’s set to eventually replace Pokémon TCG Online, the previous digital iteration of the game.',
          description1: 'In Pokémon TCG Live, players collect digital cards, build decks, and battle against opponents from around the world. The game stays faithful to the core mechanics of the physical Pokémon Trading Card Game, where players use decks of Pokémon, Trainer, and Energy cards to defeat their opponent is Pokémon by reducing their HP to zero. The first player to knock out six opposing Pokémon wins the match.',
          description2: 'Pokémon TCG Live introduces enhanced visuals, updated features, and more accessible gameplay mechanics for both newcomers and experienced players. It’s available on PC, Mac, iOS, and Android devices, allowing players to enjoy the Pokémon TCG across various platforms.',
          play: 'Pokémon Cards: These are the creatures you battle with. Each has HP, attacks, and sometimes special abilities. ',
          play1: 'Winning Condition: Players take turns playing cards, attacking with their Pokémon, and using Trainer or Item cards to support their strategy. The goal is to knock out your opponent’s Pokémon and claim prize cards. The first player to take six prize cards wins.',
          play2: 'Attack and Retreat: Once powered up with Energy, the Active Pokémon can attack the opponent is Active Pokémon. Players can also retreat their Active Pokémon, swapping it with one on the Bench if they want a different Pokémon in battle.',
          fileSize: '96 MB',
          version: '1.18.0',
          time: 'Aug 30, 2024',
          Appto: 'https://apps.apple.com/us/app/pok%C3%A9mon-tcg-live/id1557962344',
          Playto: 'https://play.google.com/store/apps/details?id=com.pokemon.pokemontcgl'
      },    {
        img: '/Card/ShadowverseCCG.webp',
          title: 'Shadowverse CCG',
          description: 'Shadowverse is a digital collectible card game (CCG) developed by Cygames and originally released in 2016. It quickly gained popularity for its deep strategy, stunning anime-inspired artwork, and competitive gameplay. With over 600 cards available at launch and multiple expansions since, Shadowverse offers a vast array of strategic possibilities, making it one of the most popular CCGs in Japan and across the globe.',
          description1: 'Set in a fantasy world, Shadowverse features a range of beautifully illustrated cards categorized into several classes, each with unique playstyles and mechanics. The game takes inspiration from traditional CCGs but adds its own twist with mechanics like "Evolve," which allows players to power up their creatures mid-game.',
          description2: 'The gameplay revolves around building decks from one of eight classes, each representing a different character and playstyle. These include Elves, Dragons, Vampires, Mages, and more. Matches are turn-based, with players summoning followers, casting spells, and using amulets to outwit their opponent and reduce their leader is life points to zero.',
          play: 'Objective: The goal of a match is to reduce your opponent is leader (character’s) health from 20 to 0. This is achieved by summoning creatures (called "followers"), casting spells, and using abilities from a player’s deck of 40 cards. ',
          play1: 'Dragoncraft: Dragoncraft excels in ramping up play points quickly to summon massive creatures. It also features the Overflow mechanic, which activates when you have 7 or more play points, making cards stronger.',
          play2: 'One of the standout features of Shadowverse is the Evolution mechanic. Starting in the fifth turn, players can evolve their followers, making them stronger and often giving them new abilities. Evolving followers costs one evolution point, and each player has a limited number of points to use throughout the match. This adds an extra layer of strategy as players must decide when to use their evolution points for maximum impact. ',
          fileSize: '73 MB',
          version: '4.6.1',
          time: 'Jul 5, 2024',
          Appto: 'https://apps.apple.com/us/app/shadowverse-ccg/id1091512762',
          Playto: 'https://play.google.com/store/apps/details?id=com.cygames.Shadowverse'
      },  
      //   {
      //   img: '/Card/Callofduty.webp',
      //     title: 'Call of Duty: Mobile Season 8',
      //     description: '',
      //     description1: '',
      //     description2: '',
      //     play: ' ',
      //     play1: '',
      //     play2: ' ',
      //     fileSize: '',
      //     version: '',
      //     time: '',
      //     Appto: '',
      //     Playto: ''
      // },
    


]
