export const PuzzlePhoto = [
    {
        img: '/Puzzle/TearsCompanion.webp',
        title: 'Tears Companions',
        description: 'TearsCompanion is an evocative and immersive narrative-driven adventure game that combines elements of mystery, exploration, and emotional storytelling. Set in a beautifully crafted world teeming with atmosphere, the game invites players to embark on a journey through a visually stunning and emotionally charged landscape, uncovering secrets and forming deep connections along the way.',
        description1: 'The game is set in a richly detailed world that seamlessly blends fantastical elements with emotional depth. Players find themselves in a unique, story-rich environment where every corner holds a story, every character has a hidden past, and every choice impacts the unfolding narrative. The game is art style is a mix of hand-drawn and digital techniques, creating a visually striking world that feels both dreamlike and grounded in its emotional resonance.',
        description2: 'TearsCompanion revolves around a central narrative that explores themes of loss, healing, and the human condition. Players take on the role of a protagonist who encounters a mysterious entity known as the "Companion," a being that guides them through a series of emotionally charged scenarios and puzzles. The Companion, a blend of both friend and enigma, aids players in uncovering the truth behind their own past and the world they inhabit.',
        play: 'Starting the Game: Begin by launching TearsCompanion. You’ll be greeted with the main menu, where you can start a new game, load a previous save, or access options and settings. If you’re new to the game, select “New Game” to begin your journey. ',
        play1: 'Understanding the Controls: Familiarize yourself with the game’s controls. TearsCompanion typically uses a combination of keyboard and mouse inputs (or a game controller, if supported). Controls include movement, interaction, and dialogue selection. Review the control settings in the options menu to adjust them to your preference.',
        play2: 'Exploring the World: As you start the game, you’ll find yourself in a richly detailed environment. Move your character around using the directional controls to explore your surroundings. Pay attention to the visual and auditory cues that may indicate interactive elements or points of interest. ',
        fileSize: '97 MB',
        version: '1.4.12',
        time: 'Jun 23, 2024',
        Appto: 'https://apps.apple.com/us/app/tears-companion/id6449003066',
        Playto: 'https://play.google.com/store/apps/details?id=com.SoftwareNotion.TearsCompanion&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/TearsCompanion/TearsCompanion1.webp','/Puzzle/PuzzleScreenshot/TearsCompanion/TearsCompanion2.webp','/Puzzle/PuzzleScreenshot/TearsCompanion/TearsCompanion3.webp','/Puzzle/PuzzleScreenshot/TearsCompanion/TearsCompanion4.webp','/Puzzle/PuzzleScreenshot/TearsCompanion/TearsCompanion5.webp','/Puzzle/PuzzleScreenshot/TearsCompanion/TearsCompanion6.webp']
    },
    {
        img: '/Puzzle/Babaisyou.webp',
        title: 'Baba Is You',
        description: 'Baba Is You is an innovative and critically acclaimed puzzle game that challenges traditional game mechanics by allowing players to manipulate the rules of the game itself. Developed by Finnish designer Arvi Teikari, the game offers a fresh and creative approach to puzzle-solving through its unique rule-bending mechanics and minimalistic yet charming visual style.',
        description1: 'In Baba Is You, players control Baba, a small white creature, as they navigate through a series of increasingly complex levels. The game is core mechanic revolves around manipulating the game’s rules to solve puzzles. Each level is composed of a grid-based environment where various objects and rules are represented by simple, readable text blocks. These text blocks can be moved and rearranged to change how the game functions.',
        description2: 'The primary objective of Baba Is You is to reach a specific goal, usually denoted by a flag or other object, by solving puzzles that require creative thinking and experimentation. The game’s key feature is its rule manipulation system. Rules are expressed as phrases like “Baba is You” or “Flag is Win,” and these phrases can be altered by moving the text blocks around the grid. For example, if the rule is “Baba is You,” then the player controls Baba. If the rule is changed to “Rock is You,” then the player would control rocks instead.',
        play: 'Getting Started: Launch Baba Is You from your device. You’ll be greeted with the main menu, where you can start a new game, continue from a previous save, or access options. Select “New Game” to begin your puzzle-solving journey.Manipulating Rules: The key to solving puzzles in Baba Is You is manipulating the rules. Each level has a set of rules that dictate how objects interact. For example, if the rule “Baba is You” is in place, you control Baba. If you change the rule to “Rock is You,” you’ll control rocks instead. Experiment with different rule combinations to see how they affect the game.',
        play1: 'Understanding the Basics: Baba Is You operates on a grid-based system where each level consists of a series of text blocks and objects. The text blocks represent rules of the game, such as “Baba is You” or “Flag is Win.” Objects in the game include Baba, walls, flags, and other elements that interact based on the rules.',
        play2: ' Moving and Interacting: Use the arrow keys or directional controls to move Baba or other objects around the grid. To interact with text blocks, move Baba or other objects into them to push or pull them. The game’s interface is designed to be intuitive, allowing you to interact with and rearrange text blocks easily.',
        fileSize: '95 MB',
        version: '535.0',
        time: 'Jun 20, 2024',
        Appto: 'https://apps.apple.com/us/app/baba-is-you/id1517281887',
        Playto: 'https://play.google.com/store/apps/details?id=org.hempuli.baba&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/BabaIsYou/BabaIsYou1.webp','/Puzzle/PuzzleScreenshot/BabaIsYou/BabaIsYou2.webp','/Puzzle/PuzzleScreenshot/BabaIsYou/BabaIsYou3.webp','/Puzzle/PuzzleScreenshot/BabaIsYou/BabaIsYou4.webp','/Puzzle/PuzzleScreenshot/BabaIsYou/BabaIsYou5.webp','/Puzzle/PuzzleScreenshot/BabaIsYou/BabaIsYou6.webp','/Puzzle/PuzzleScreenshot/BabaIsYou/BabaIsYou7.webp','/Puzzle/PuzzleScreenshot/BabaIsYou/BabaIsYou8.webp']
    }, {
        img: '/Puzzle/TetrisBlockPuzzle.webp',
        title: 'Tetris® Block Puzzle',
        description: 'Tetris® Block Puzzle is a captivating and strategic puzzle game that builds on the classic Tetris® formula while introducing new challenges and gameplay elements. Developed by The Tetris Company, this iteration of Tetris® brings the timeless appeal of falling blocks into a fresh and engaging format that tests both your spatial reasoning and strategic planning skills.',
        description1: 'At its core, Tetris® Block Puzzle retains the beloved mechanics of the original Tetris® game: players manipulate falling tetrominoes (geometric shapes composed of four blocks) to create and clear lines on the playfield. However, this version offers additional features and gameplay modes that enhance the classic experience and provide new ways to enjoy the game.',
        description2: 'The game presents a grid-based playfield where tetrominoes fall from the top of the screen. Players must rotate and position these blocks to fit into the available space, aiming to complete horizontal lines. When a line is completed, it disappears, and the player earns points. The goal is to keep the playfield clear and prevent the blocks from reaching the top of the screen.',
        play: 'Starting the Game: Launch Tetris® Block Puzzle on your device. You’ll be presented with the main menu, where you can choose to start a new game, enter a specific game mode, or access settings. Select “New Game” or your preferred mode to begin.',
        play1: 'Understanding the Playfield: The game features a grid-based playfield where tetrominoes will fall from the top. The grid is where you’ll place and arrange the falling blocks. Familiarize yourself with the size and shape of the playfield to better plan your moves.',
        play2: 'Using Power-Ups and Special Features: Tetris® Block Puzzle may include power-ups or special features that can help you clear lines or manage the playfield. These can include items that slow down the fall of tetrominoes, clear specific lines, or provide other benefits. Use these strategically to improve your gameplay. ',
        fileSize: '133 MB',
        version: '1.5.1053',
        time: 'Sep 13, 2024',
        Appto: 'https://apps.apple.com/us/app/tetris-block-puzzle/id6448698584',
        Playto: 'https://play.google.com/store/apps/details?id=com.playstudios.tetris4&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/TetrisBlockPuzzle/BlockPuzzle1.webp','/Puzzle/PuzzleScreenshot/TetrisBlockPuzzle/BlockPuzzle2.webp','/Puzzle/PuzzleScreenshot/TetrisBlockPuzzle/BlockPuzzle3.webp','/Puzzle/PuzzleScreenshot/TetrisBlockPuzzle/BlockPuzzle4.webp','/Puzzle/PuzzleScreenshot/TetrisBlockPuzzle/BlockPuzzle5.webp','/Puzzle/PuzzleScreenshot/TetrisBlockPuzzle/BlockPuzzle6.webp']
    }, {
        img: '/Puzzle/MonumentValley2.webp',
        title: 'Monument Valley 2',
        description: 'Monument Valley 2 is an enchanting and visually stunning puzzle-adventure game developed by ustwo games. As a sequel to the acclaimed original Monument Valley, this game continues to captivate players with its mesmerizing optical illusions, intricate architectural puzzles, and emotionally rich narrative.',
        description1: 'Set in a dreamlike world of impossible geometry, Monument Valley 2 invites players to guide a mother and her child through a series of beautifully crafted levels. The game’s art style is characterized by its minimalist design, featuring vibrant colors, elegant structures, and surreal landscapes that defy the laws of physics. Each level is a meticulously designed puzzle, where players must manipulate the environment to help the characters navigate through complex, Escher-like structures.',
        description2: 'Monument Valley 2 also places a strong emphasis on storytelling and emotional depth. The narrative unfolds through the interactions between the mother and child, exploring themes of growth, connection, and the passage of time. The game’s story is told through visual storytelling and subtle hints within the environment, creating an evocative and poignant experience without relying heavily on text.',
        play: 'Getting Started: Launch Monument Valley 2 on your device. You’ll be greeted with the main menu, where you can start a new game, continue from a previous save, or access settings. Select “New Game” to begin your journey with the mother and child. ',
        play1: 'Interacting with Characters: As you guide the mother and child through the levels, you’ll need to help them work together to overcome obstacles. The child can interact with certain elements of the environment, and their actions may impact how the mother can move. Coordinate their movements to solve puzzles effectively.',
        play2: 'Exploring Perspectives: The game heavily relies on perspective and optical illusions. Rotating or shifting the environment may change how the structures align, creating new pathways or revealing hidden areas. Be open to experimenting with different viewpoints to uncover the solution to each puzzle. ',
        fileSize: '287 MB',
        version: '3.7.501',
        time: 'Sep 4, 2024',
        Appto: 'https://apps.apple.com/us/app/monument-valley-2/id1187265767',
        Playto: 'https://play.google.com/store/apps/details?id=com.ustwo.monumentvalley2&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/MonumentValley/MonumentValley1.webp','/Puzzle/PuzzleScreenshot/MonumentValley/MonumentValley2.webp','/Puzzle/PuzzleScreenshot/MonumentValley/MonumentValley3.webp','/Puzzle/PuzzleScreenshot/MonumentValley/MonumentValley4.webp','/Puzzle/PuzzleScreenshot/MonumentValley/MonumentValley5.webp','/Puzzle/PuzzleScreenshot/MonumentValley/MonumentValley6.webp']
    }, {
        img: '/Puzzle/TypomanRemastered.webp',
        title: 'Typoman Remastered',
        description: 'Typoman Remastered is an imaginative and visually striking puzzle-platformer that combines wordplay with atmospheric storytelling. Developed by Brainseed Factory, this remastered version of the original Typoman brings enhanced graphics and refined gameplay to the unique world of typographic adventure. The game offers a captivating experience where language and letters are central to solving puzzles and progressing through the narrative.',
        description1: 'Set in a dark and enigmatic world where letters and words shape the environment, Typoman Remastered invites players to guide the protagonist, a character made of letters, through a series of increasingly complex levels. The game’s setting is a dystopian landscape filled with typographic elements that are both obstacles and tools for solving puzzles. The atmosphere is moody and immersive, with a blend of eerie environments and clever word-based mechanics.',
        description2: 'The core gameplay of Typoman Remastered revolves around manipulating letters and words to interact with the game world. As players navigate through the levels, they encounter various challenges that require them to rearrange, combine, or modify letters to create words that affect the environment. For example, forming the word “OPEN” might unlock a door, while creating the word “STOP” could halt moving platforms or hazards.',
        play: 'Starting the Game: Launch Typoman Remastered on your device. You’ll be greeted with the main menu, where you can start a new game, load a previous save, or access options. Select “New Game” to begin your adventure. ',
        play1: 'Understanding the Gameplay Mechanics: In Typoman Remastered, the primary mechanic involves manipulating letters and words to interact with the environment. Your character, made of letters, can move, jump, and interact with various elements. The goal is to use language to solve puzzles and advance through the levels.',
        play2: 'Navigating the Environment: Use the directional controls (arrow keys or joystick) to move your character left or right. To jump, use the jump button. Explore the environment and look for letters and words that you can manipulate. The game’s world is filled with typographic elements that you’ll need to interact with to progress. ',
        fileSize: 'Jun 27, 2022',
        version: '1.2.20',
        time: 'Aug 31, 2024',
        Appto: 'https://apps.apple.com/us/app/typoman-remastered/id1263413091',
        Playto: 'https://play.google.com/store/apps/details?id=com.BrainseedFactory.Typoman&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/TypomanRemastered/TypomanRemastered1.webp','/Puzzle/PuzzleScreenshot/TypomanRemastered/TypomanRemastered2.webp','/Puzzle/PuzzleScreenshot/TypomanRemastered/TypomanRemastered3.webp','/Puzzle/PuzzleScreenshot/TypomanRemastered/TypomanRemastered4.webp','/Puzzle/PuzzleScreenshot/TypomanRemastered/TypomanRemastered5.webp','/Puzzle/PuzzleScreenshot/TypomanRemastered/TypomanRemastered6.webp','/Puzzle/PuzzleScreenshot/TypomanRemastered/TypomanRemastered7.webp']
    }, {
        img: '/Puzzle/LAYTONBROTHERSMYSTERYROOM.webp',
        title: 'LAYTON BROTHERS MYSTERY ROOM',
        description: 'Layton Brothers: Mystery Room is an engaging and intellectually stimulating detective adventure game developed by Level-5. Set in the same universe as the popular Professor Layton series, this game offers a fresh take on the series signature puzzle-solving gameplay, placing players in the role of a detective tasked with solving intricate and enigmatic cases.',
        description1: 'In Layton Brothers: Mystery Room, players step into the shoes of a young detective named Alfendi Layton, who is the son of the renowned Professor Layton. Alongside his partner, the skilled forensic scientist Katrielle Layton, players investigate a series of challenging murder mysteries that require keen observation, logical deduction, and a deep understanding of clues and evidence.',
        description2: 'Layton Brothers: Mystery Room is notable for its innovative gameplay mechanics that blend traditional point-and-click adventure elements with forensic investigation. Players interact with various objects and characters by tapping on the screen, collecting crucial evidence, and solving a variety of puzzles and mini-games that are integral to the investigation process. These puzzles range from logic and pattern recognition challenges to more complex riddles, providing a diverse and engaging gameplay experience.',
        play: 'Getting Started: Launch Layton Brothers: Mystery Room on your device. You’ll be greeted with the main menu, where you can start a new case, continue a previous investigation, or access settings. Select “New Game” to begin your journey as a detective. ',
        play1: 'Understanding the Interface: Familiarize yourself with the game’s interface. You’ll have access to a variety of tools and menus, including evidence collection, case notes, and puzzle-solving options. The interface is designed to be user-friendly, with clear icons and options for interacting with the game’s elements.',
        play2: 'Solving Puzzles: The game features a variety of puzzles that are integral to the investigation process. These puzzles can range from logic challenges to pattern recognition tasks. Solve these puzzles to unlock additional clues or progress through the case. Each puzzle is designed to test your deductive skills and provide insights into the case.   ',
        fileSize: '344MB',
        version: '1.1.2',
        time: 'Aug 28, 2024',
        Appto: 'https://apps.apple.com/us/app/layton-brothers-mystery-room/id640517092',
        Playto: 'https://play.google.com/store/apps/details?id=com.Level_5.MysteryRoomENG&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/LAYTONBROTHERS/LAYTONBROTHERS1.webp','/Puzzle/PuzzleScreenshot/LAYTONBROTHERS/LAYTONBROTHERS2.webp','/Puzzle/PuzzleScreenshot/LAYTONBROTHERS/LAYTONBROTHERS3.webp','/Puzzle/PuzzleScreenshot/LAYTONBROTHERS/LAYTONBROTHERS4.webp','/Puzzle/PuzzleScreenshot/LAYTONBROTHERS/LAYTONBROTHERS5.webp','/Puzzle/PuzzleScreenshot/LAYTONBROTHERS/LAYTONBROTHERS6.webp','/Puzzle/PuzzleScreenshot/LAYTONBROTHERS/LAYTONBROTHERS7.webp','/Puzzle/PuzzleScreenshot/LAYTONBROTHERS/LAYTONBROTHERS8.webp']
    }, {
        img: '/Puzzle/NonogramsKatana.webp',
        title: 'Nonograms Katana',
        description: 'Nonograms Katana is an engaging and visually captivating puzzle game that brings a fresh twist to the classic nonogram genre, also known as Picross or Griddlers. Developed by [Developer is Name], this game combines traditional nonogram mechanics with a unique aesthetic and additional gameplay elements to create a compelling experience for puzzle enthusiasts.',
        description1: 'In Nonograms Katana, players are tasked with solving nonogram puzzles, which are logic-based grid puzzles where numbers along the edges of the grid indicate the lengths of consecutive filled cells in each row and column. The goal is to fill in the grid based on these clues to reveal a hidden image. The images created by solving these puzzles range from simple patterns to intricate designs, providing a satisfying visual reward for completing each puzzle.',
        description2: 'What sets Nonograms Katana apart from other nonogram games is its distinctive theme and presentation. The game features a vibrant, Japanese-inspired aesthetic, with intricate designs and a dynamic art style that adds a layer of visual appeal to the puzzle-solving experience. The use of katana (Japanese swords) as a thematic element enhances the game’s atmosphere, blending traditional puzzle mechanics with a unique cultural motif.',
        play: 'Starting the Game: Launch Nonograms Katana on your device. You’ll be presented with the main menu, where you can start a new puzzle, continue from where you left off, or access settings. Select “New Puzzle” or your desired option to begin. ',
        play1: 'Understanding the Grid and Clues: The game features a grid with numbers along the top and side. These numbers indicate how many consecutive cells should be filled in each row and column. For example, a clue of “3” means that there is a block of three consecutive filled cells in that row or column.',
        play2: 'Filling in the Grid: Use the touch controls to fill in the cells of the grid. Tap on a cell to mark it as filled, and tap again to mark it as empty or to remove the mark. Your goal is to use the numerical clues to determine which cells should be filled in to complete the image. ',
        fileSize: 'Mar 12, 2014',
        version: '19.04',
        time: 'Jul 29, 2024',
        Appto: 'https://apps.apple.com/us/app/nonograms-katana/id1037710023',
        Playto: 'https://play.google.com/store/apps/details?id=com.ucdevs.jcross&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/NonogramsKatana/NonogramsKatana1.webp','/Puzzle/PuzzleScreenshot/NonogramsKatana/NonogramsKatana2.webp','/Puzzle/PuzzleScreenshot/NonogramsKatana/NonogramsKatana3.webp','/Puzzle/PuzzleScreenshot/NonogramsKatana/NonogramsKatana4.webp','/Puzzle/PuzzleScreenshot/NonogramsKatana/NonogramsKatana5.webp','/Puzzle/PuzzleScreenshot/NonogramsKatana/NonogramsKatana6.webp','/Puzzle/PuzzleScreenshot/NonogramsKatana/NonogramsKatana7.webp','/Puzzle/PuzzleScreenshot/NonogramsKatana/NonogramsKatana8.webp']
    }, {
        img: '/Puzzle/HumanFallFlat.webp',
        title: 'Human Fall Flat',
        description: 'Human: Fall Flat is a quirky and highly entertaining physics-based puzzle platformer developed by No Brakes Games. Known for its whimsical and humorous gameplay, the game provides a refreshing take on the platformer genre with its focus on ragdoll physics and cooperative play.',
        description1: ',In Human: Fall Flat, players take on the role of Bob, a wobbly human character with a peculiar control scheme. Bob is movements are governed by a realistic ragdoll physics engine, which means he can stumble, flail, and flop around in a hilariously unpredictable manner. The game is core mechanics revolve around using Bob’s wobbly body to navigate through a series of inventive and challenging levels filled with puzzles and obstacles.',
        description2: 'The game is set in an open-world environment with various themed levels, each presenting unique challenges and opportunities for creative problem-solving. Players must manipulate objects, solve physics-based puzzles, and explore the environment to progress through each level. The open-ended nature of the puzzles allows for multiple approaches and solutions, encouraging players to experiment and think outside the box.',
        play: 'Starting the Game: Launch Human: Fall Flat on your platform of choice. You’ll be presented with the main menu, where you can start a new game, continue from a previous save, or access settings. Select “New Game” to begin your adventure.',
        play1: 'Understanding Controls: Familiarize yourself with the controls. The basic controls include moving (usually with the left joystick or arrow keys), jumping, and grabbing objects (typically with the right trigger or a specific button). The controls can vary depending on the platform you’re playing on, so check the in-game control settings if needed.',
        play2: 'Navigating the Environment: Use the movement controls to maneuver your character through the level. Bob’s ragdoll physics mean that his movements can be unpredictable, so be prepared for a lot of stumbling and flailing. Move cautiously and use the environment to your advantage to avoid falling or getting stuck. ',
        fileSize: '2 GB',
        version: '1.14',
        time: 'Sep 13, 2023',
        Appto: 'https://apps.apple.com/us/app/human-fall-flat/id1438091392',
        Playto: 'https://play.google.com/store/apps/details?id=com.and.games505.humanfallflat&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/HumanFallFlat/HumanFallFlat1.webp','/Puzzle/PuzzleScreenshot/HumanFallFlat/HumanFallFlat2.webp','/Puzzle/PuzzleScreenshot/HumanFallFlat/HumanFallFlat3.webp','/Puzzle/PuzzleScreenshot/HumanFallFlat/HumanFallFlat4.webp','/Puzzle/PuzzleScreenshot/HumanFallFlat/HumanFallFlat5.webp','/Puzzle/PuzzleScreenshot/HumanFallFlat/HumanFallFlat6.webp','/Puzzle/PuzzleScreenshot/HumanFallFlat/HumanFallFlat7.webp','/Puzzle/PuzzleScreenshot/HumanFallFlat/HumanFallFlat8.webp']
    }, {
        img: '/Puzzle/Gorogoa.webp',
        title: 'Gorogoa',
        description: 'Gorogoa is a visually stunning and intellectually stimulating puzzle game developed by Jason Roberts and published by Annapurna Interactive. Released in December 2017, the game stands out for its unique approach to storytelling and puzzle design, offering an experience that is both artistic and deeply engaging.',
        description1: 'In Gorogoa, players are introduced to a beautifully hand-drawn world where puzzles are solved by manipulating a series of illustrated panels. The game’s central mechanic involves interacting with these panels, which can be resized, moved, and combined in various ways to reveal hidden connections and progress through the narrative. The puzzles are integrated seamlessly into the story, creating a compelling and immersive experience.',
        description2: 'The game’s visual design is one of its most striking features. Each panel is intricately illustrated, with a watercolor-like aesthetic that brings the game’s world to life. The artwork is both detailed and evocative, contributing to the game’s overall atmosphere and enhancing the storytelling. The panels often depict scenes or objects that can be manipulated to uncover new elements or to create connections between different parts of the narrative.',
        play: 'Starting the Game: Launch Gorogoa on your chosen platform. You’ll be greeted with the main menu, where you can start a new game, continue from a previous save, or access settings. Select “New Game” to begin your journey. ',
        play1: 'Understanding the Interface: Familiarize yourself with the game’s interface. The primary gameplay element consists of several panels that you can interact with. These panels represent different scenes or objects in the game. You’ll use these panels to solve puzzles and advance through the narrative.',
        play2: 'Interacting with Panels: Tap or click on the panels to interact with them. You can move, resize, and overlay panels to create connections or reveal hidden elements. The panels can be manipulated in various ways, such as sliding them around, zooming in or out, or stacking them to create new perspectives. ',
        fileSize: 'May 23, 2024',
        version: '1.2.1',
        time: 'May 23, 2024',
        Appto: 'https://play.google.com/store/apps/details?id=unity.Annapurna.Gorogoa&hl=en-US',
        Playto: 'https://apps.apple.com/us/app/gorogoa/id1269225754',
        screenShot:['/Puzzle/PuzzleScreenshot/Gorogoa/Gorogoa1.png','/Puzzle/PuzzleScreenshot/Gorogoa/Gorogoa2.png','/Puzzle/PuzzleScreenshot/Gorogoa/Gorogoa3.png','/Puzzle/PuzzleScreenshot/Gorogoa/Gorogoa4.png','/Puzzle/PuzzleScreenshot/Gorogoa/Gorogoa5.png','/Puzzle/PuzzleScreenshot/Gorogoa/Gorogoa6.png']
    }, {
        img: '/Puzzle/Sokobond.webp',
        title: 'Sokobond',
        description: 'Sokobond is a cleverly designed and visually appealing puzzle game developed by Alan Hazelden and published by Draknek. Released in 2015, the game presents a unique twist on the classic Sokoban puzzle genre, incorporating chemistry-themed mechanics into its gameplay.',
        description1: 'In Sokobond, players are tasked with solving a series of puzzles that revolve around chemical bonding and molecular structure. Unlike traditional Sokoban games, where players push boxes to solve puzzles, Sokobond challenges players to connect atoms to form molecules. The goal is to manipulate and bond different types of atoms to complete molecular structures, adhering to the rules of chemistry.',
        description2: 'The game features a minimalist and aesthetically pleasing design, with a clean and simple visual style that focuses on the core mechanics. Each puzzle consists of a grid where atoms are placed, and players must connect them using a set of allowed moves to form the correct molecules. The puzzles gradually increase in complexity, introducing new types of atoms and bonding rules as players progress through the game.',
        play: 'Starting the Game: Launch Sokobond on your platform of choice. You’ll be greeted with the main menu, where you can start a new game, load a previous save, or access settings. Select “New Game” or your desired option to begin. ',
        play1: 'Recognizing Atoms and Bonds: Learn about the different types of atoms and bonds in the game. Each atom has a specific color and shape, representing different elements. The goal is to connect these atoms correctly to create the desired molecular structures. The bonding rules are based on basic chemistry principles.',
        play2: 'Enjoying the Experience: Take your time to enjoy the game’s elegant design and soothing soundtrack. The combination of thoughtful puzzle mechanics and visual aesthetics creates a relaxing and immersive experience. ',
        fileSize: 'Sep 10, 2024',
        version: '2.0.4',
        time: 'Sep 10, 2024',
        Appto: 'https://apps.apple.com/us/app/sokobond/id1047551452',
        Playto: 'https://play.google.com/store/apps/details?id=air.com.sokobond&hl=en-US',
        screenShot:['/Puzzle/PuzzleScreenshot/Sokobond/Sokobond2.webp','/Puzzle/PuzzleScreenshot/Sokobond/Sokobond1.webp','/Puzzle/PuzzleScreenshot/Sokobond/Sokobond3.webp','/Puzzle/PuzzleScreenshot/Sokobond/Sokobond4.webp','/Puzzle/PuzzleScreenshot/Sokobond/Sokobond5.webp','/Puzzle/PuzzleScreenshot/Sokobond/Sokobond6.webp']
    },

]