export const RacingPhoto = [
    {
        img: '/Racing/Asphalt9Legends.webp',
        title: 'Asphalt Legends Unite',
        description: 'Asphalt 9: Legends is a high-octane racing game developed by Gameloft and is part of the popular Asphalt series. Released in 2018, it brings players into the fast-paced world of street racing, where they can experience the thrill of driving some of the world is most powerful and luxurious cars.',
        description1: 'In Asphalt 9, players embark on an exhilarating journey with a diverse range of vehicles, from sleek sports cars to high-performance supercars. The game boasts a roster of over 60 cars, each meticulously designed with attention to detail. Iconic brands like Ferrari, Lamborghini, Porsche, and many others are featured, allowing players to take the wheel of their dream machines.',
        description2: 'The game is set in a variety of stunning locations around the globe. Players race through dynamic and visually striking environments, including bustling city streets, winding mountain roads, and scenic coastal areas. Each track is designed with multiple routes and shortcuts, adding a layer of strategy to the gameplay.',
        play: ' TouchDrive System: Asphalt 9 uses the TouchDrive control system, simplifying gameplay. Swipe left or right to steer your car, tap the screen to activate boosts or perform stunts, and the game handles acceleration and braking automatically.',
        play1: 'Unlocking Cars: Start with a basic car and complete races to earn credits and unlock new vehicles. Higher-tier cars are more powerful and have better performance stats.',
        play2: 'Single-Player Mode: Begin with the single-player campaign to familiarize yourself with the game mechanics. Complete missions and races to earn rewards and progress through the career mode. ',
        fileSize: '3 GB',
        version: '24.0.6a',
        time: '26 Aug 2024',
        Appto: 'https://apps.apple.com/ph/app/asphalt-legends-unite/id805603214',
        Playto: 'https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA9HM&hl=en_IN&pli=1'
    }, {
        img: '/Racing/CarXDriftRacing2.webp',
        title: 'CarX Drift Racing 2',
        description: 'CarX Drift Racing 2 is a popular drifting-focused racing game developed by CarX Technologies. Released as a sequel to the highly acclaimed CarX Drift Racing, this game builds on its predecessor is success with improved graphics, enhanced physics, and a more immersive drifting experience. It is available on iOS, Android, and various other platforms, catering to both casual gamers and drift enthusiasts alike.',
        description1: 'In CarX Drift Racing 2, players dive into the world of drift racing, where precision and control are key. The game features a wide selection of cars, each with customizable parts and tuning options that allow players to tweak their vehicles to perfection. From classic muscle cars to modern sports cars, the roster is designed to cater to a variety of drifting styles and preferences.',
        description2: 'The game is renowned for its realistic physics engine, which simulates car behavior with impressive accuracy. The drifting mechanics are finely tuned, offering a true-to-life drifting experience that requires skill and practice. The physics engine accounts for factors like weight distribution, tire grip, and road conditions, providing a dynamic and challenging driving experience.',
        play: 'Download and Installation: CarX Drift Racing 2 is available on iOS, Android, and other platforms. Download the game from your app store or gaming platform and install it on your device. ',
        play1: 'Steering: Use the on-screen steering wheel or tilt controls to steer your car. Adjust sensitivity settings to find a control scheme that suits you.Throttle and Brake: Use the gas and brake buttons to control your speed. Smooth inputs are crucial for maintaining control while drifting.',
        play2: 'Unlocking Cars: Start with a basic car and earn in-game currency by completing races and challenges. Use this currency to unlock new cars or purchase upgrades. ',
        fileSize: '2 GB',
        version: '1.33.0',
        time: '7 Sept 2024',
        Appto: 'https://apps.apple.com/ph/app/carx-drift-racing-2/id1198510863',
        Playto: 'https://play.google.com/store/apps/details?id=com.carxtech.carxdr2&hl=en_IN'
    }, {
        img: '/Racing/needforspeed.webp',
        title: 'Need for Speed™ No Limits',
        description: 'Need for Speed™ No Limits is a high-octane mobile racing game developed by Firemonkeys Studios and published by Electronic Arts. Released in 2015, it brings the thrilling street racing experience of the Need for Speed franchise to mobile devices, delivering fast-paced gameplay and an engaging racing environment.',
        description1: 'In Need for Speed™ No Limits, players dive into the underground world of street racing. The game features an extensive collection of over 30 licensed cars, including iconic models from brands like Ferrari, Lamborghini, and Nissan. Each car is designed with meticulous attention to detail, capturing their real-world counterparts look and feel.',
        description2: 'The game is story-driven campaign unfolds through a series of missions and races, set in a vibrant cityscape filled with neon lights and urban chaos. Players navigate through a variety of environments, from bustling city streets to dark alleyways, all rendered with impressive graphics that enhance the immersive experience.',
        play: 'Download and Installation: Need for Speed™ No Limits is available on iOS and Android devices. Download the game from your app store and install it on your device.Creating an Account: Sign in with an EA account or create one to save your progress and access online features. Follow the on-screen instructions to set up your account. ',
        play1: 'Steering: Use the on-screen steering wheel or tilt controls to steer your car. Adjust sensitivity settings to find a comfortable control scheme.Accelerating and Braking: Tap the gas and brake buttons to control your speed. Smooth acceleration and braking are crucial for maintaining control.',
        play2: 'Unlocking Cars: Earn in-game currency and complete missions to unlock new cars. Each car has unique stats and abilities.Customizing Cars: Access the garage to customize your car’s appearance and performance. Apply paint jobs, decals, and performance upgrades to enhance your vehicle.  ',
        fileSize: '166 MB',
        version: '7.9.0',
        time: '5 Sept 2024',
        Appto: 'https://apps.apple.com/ph/app/need-for-speed-no-limits/id883393043',
        Playto: 'https://play.google.com/store/apps/details?id=com.ea.game.nfs14_row&hl=en_IN'
    }, {
        img: '/Racing/realracing.webp',
        title: 'Real Racing 3',
        description: 'Real Racing 3 is a critically acclaimed mobile racing game developed by Firemonkeys Studios and published by Electronic Arts. It was released on February 28, 2013, and is the third installment in the Real Racing series. Unlike many other arcade-style racing games, Real Racing 3 strives for a more realistic driving experience, focusing on real-world cars, tracks, and racing events.',
        description1: 'The game features a massive roster of over 250 officially licensed cars from more than 30 real-life manufacturers. Players can drive vehicles from prestigious brands like Ferrari, Lamborghini, Porsche, Bugatti, Audi, and many others. Each car is meticulously modeled to reflect its real-world counterpart, not only in terms of looks but also performance. This adds to the game’s immersive feel and creates a more authentic racing experience.',
        description2: 'What sets Real Racing 3 apart is its dedication to realism, particularly with its track selection. The game includes over 19 real-world circuits from locations across the globe, such as Silverstone, Hockenheimring, Le Mans, Circuit of the Americas, and Yas Marina, to name a few. These tracks are recreated in high detail, with accurate layouts and weather effects, giving players a true-to-life racing atmosphere.',
        play: 'Download and Installation: Real Racing 3 is available on iOS and Android devices. Download it from your app store and install it. The initial download is about 2GB, but subsequent updates can increase the total size significantly. ',
        play1: 'Assist Settings: Real Racing 3 includes customizable driving assists like traction control, braking assist, and steering assist. Beginners may want to keep these settings on, while experienced players can disable them for more control and challenge.',
        play2: 'Unlocking Cars: As you progress through the game, you will earn in-game currency to buy new cars. Additionally, you can unlock premium cars by purchasing them with gold (premium currency). ',
        fileSize: '98 MB',
        version: '12.6.8',
        time: '9 Sept 2024',
        Appto: 'https://apps.apple.com/ph/app/real-racing-3/id556164350',
        Playto: 'https://play.google.com/store/apps/details?id=com.ea.games.r3_row&hl=en_IN'
    }, {
        img: '/Racing/MadOut2GrandAutoRacing.webp',
        title: 'MadOut 2: Grand Auto Racing',
        description: 'MadOut 2: Grand Auto Racing is an open-world racing game developed by MadOut Games. Released for mobile devices, this game combines high-speed racing with a vast, free-roaming environment, offering players a mix of structured races and open-world exploration.',
        description1: 'The game features a large, detailed city environment that players can freely navigate. This open-world aspect allows players to explore various areas, including urban streets, highways, and rural roads. The city is designed with a variety of landmarks, traffic patterns, and hidden areas, adding depth and realism to the driving experience.',
        description2: 'MadOut 2 boasts a diverse selection of vehicles, including sports cars, off-road trucks, and muscle cars. Each vehicle is designed with realistic physics and handling characteristics, allowing players to experience different driving styles and performance levels. The game includes both licensed cars and custom vehicles, giving players a wide range of options for their driving preferences.',
        play: 'Download and Installation: MadOut 2: Grand Auto Racing is available on iOS and Android devices. Download the game from your app store and install it on your device.Create an Account: Sign in with your social media account or create a guest profile to start playing. Linking an account allows you to save your progress and access multiplayer features. ',
        play1: 'Steering: Use the on-screen steering wheel or tilt controls to navigate your car. Adjust sensitivity settings in the options menu to suit your driving style.Accelerating and Braking: Use the gas and brake buttons to control your car’s speed. Smooth acceleration and braking are crucial for handling different terrains and racing situations.',
        play2: 'Weather Effects: Adapt to changing weather conditions such as rain and fog. These conditions can affect traction and visibility, so adjust your driving style accordingly.Day-Night Cycle: The dynamic day-night cycle impacts the lighting and ambiance of the city. Use this to your advantage in races and exploration. ',
        fileSize: '2 GB',
        version: '14.03',
        time: '11 Sept 2024',
        Appto: 'https://apps.apple.com/ph/app/madout-2-grand-auto-racing/id1214765807',
        Playto: 'https://play.google.com/store/apps/details?id=com.MadOut.BIG&hl=en_IN'
    }, {
        img: '/Racing/HillClimbRacing2.webp',
        title: 'Hill Climb Racing 2',
        description: 'Hill Climb Racing 2 is a popular physics-based racing game developed by Fingersoft. Released as the sequel to the highly successful Hill Climb Racing, this game takes the thrilling and challenging hill-climbing gameplay to new heights with enhanced graphics, more vehicles, and a variety of tracks.',
        description1: 'In Hill Climb Racing 2, players navigate through a series of increasingly difficult terrains and obstacles in various vehicles. The game features a diverse collection of vehicles, including cars, trucks, motorcycles, and even unconventional options like a tank and a skateboard. Each vehicle is equipped with different attributes, such as speed, handling, and grip, which influence its performance on different types of terrain.',
        description2: 'The core gameplay revolves around using precise control to drive up steep hills, over rugged landscapes, and across challenging obstacles. The physics engine simulates realistic vehicle behavior, requiring players to manage acceleration, braking, and balance to avoid tipping over or running out of fuel. Players must navigate tricky inclines, jumps, and other obstacles while striving to reach the finish line.',
        play: 'Download and Installation: Hill Climb Racing 2 is available on iOS and Android devices. Download it from your app store and install it on your device.Create an Account: Sign in with your Google Play, Apple ID, or Facebook account to save your progress and access multiplayer features. You can also play as a guest. ',
        play1: 'Acceleration and Braking: Use the on-screen gas and brake buttons to control your vehicle’s speed. Press the gas button to accelerate and the brake button to slow down or reverse.Balance Control: Tilt your device to control the vehicle’s tilt. Balancing your vehicle is crucial for navigating steep inclines and rough terrain.',
        play2: 'Customizing Vehicles: Access the garage to customize your vehicle’s appearance and performance. Upgrade components such as the engine, suspension, and tires to improve your vehicle’s capabilities. ',
        fileSize: '153 MB',
        version: '1.62.3',
        time: '6 Sept 2024',
        Appto: 'https://apps.apple.com/ph/app/hill-climb-racing-2/id1146465836',
        Playto: 'https://play.google.com/store/apps/details?id=com.fingersoft.hcr2&hl=en_IN'
    }, {
        img: '/Racing/RacingFever.webp',
        title: 'Racing Fever',
        description: 'Racing Fever is a popular mobile racing game developed by Gameguru. Released for iOS and Android devices, the game offers a blend of fast-paced driving and immersive graphics, making it a compelling choice for racing enthusiasts.',
        description1: 'In Racing Fever, players engage in high-speed races through various environments, including city streets, highways, and rural roads. The game features a wide range of vehicles, from sports cars and muscle cars to motorcycles and trucks, each with distinct attributes and performance characteristics.',
        description2: 'The gameplay focuses on both the thrill of racing and the challenge of dodging traffic. Players must navigate through dense traffic while maintaining high speeds, requiring precise control and quick reflexes. The game is physics engine provides realistic handling and driving dynamics, adding to the immersive experience.',
        play: 'Download and Installation: Racing Fever is available on iOS and Android devices. Download it from your app store and install it on your device.Create an Account: Sign in with your Google Play, Apple ID, or Facebook account to save your progress and access multiplayer features. You can also play as a guest. ',
        play1: 'Steering: Use on-screen buttons or tilt controls to steer your vehicle. The controls are designed to be intuitive, allowing you to adjust your driving style based on your preference.Acceleration and Braking: Tap the gas button to accelerate and the brake button to slow down or reverse. Smooth acceleration and braking are essential for navigating through traffic and avoiding collisions.',
        play2: ' Customizing Vehicles: Access the garage to upgrade your vehicle’s performance and appearance. Apply upgrades to improve speed, handling, and durability, and customize the car’s look with paint jobs and decals.',
        fileSize: '103MB',
        version: '1.7.1',
        time: '11 Oct 2023',
        Appto: 'https://apps.apple.com/ph/app/racing-fever/id978359164',
        Playto: 'https://play.google.com/store/apps/details?id=mobi.gameguru.racingfever&hl=en_IN'
    }, {
        img: '/Racing/csrRacing.webp',
        title: 'CSR Classics',
        description: 'CSR Classics is a drag racing game developed by Boss Alien and published by NaturalMotion Games. Released as a spin-off of the popular CSR Racing series, CSR Classics combines the thrill of high-speed drag racing with the appeal of classic and vintage cars.',
        description1: 'In CSR Classics, players engage in drag racing events using a diverse roster of iconic classic cars from the 1960s, 1970s, and 1980s. The game features an impressive selection of vehicles, including muscle cars, sports cars, and racing legends, each meticulously modeled to reflect its real-world counterpart.',
        description2: 'The core gameplay focuses on high-speed, head-to-head drag races. Players must master the timing of their gear shifts and use nitrous boosts strategically to achieve the fastest times. Unlike traditional racing games that involve circuit racing, CSR Classics centers on straight-line drag races, emphasizing precision and quick reflexes.',
        play: 'Classic Car Collection: The game features a wide range of classic cars, from American muscle cars to European sports cars. Players can acquire and upgrade these vehicles to improve performance and appearance. ',
        play1: 'Car Customization: Players can customize their classic cars with various upgrades and modifications. This includes performance enhancements such as engine upgrades, turbochargers, and nitrous systems, as well as visual customizations like paint jobs, decals, and rims.',
        play2: 'Progression and Rewards: Players progress through the game by completing races, earning in-game currency, and unlocking new content. Rewards can be used to purchase new cars, upgrades, and customizations. ',
        fileSize: '147 MB',
        version: '3.1.3',
        time: '21 Feb 2024',
        Appto: 'https://apps.apple.com/ph/app/csr-classics/id598603610',
        Playto: 'https://play.google.com/store/apps/details?id=com.naturalmotion.csrclassics&hl=en_IN'
    }, {
        img: '/Racing/RDS.webp',
        title: 'Real Driving School',
        description: 'Real Driving School is an immersive driving simulation game designed to deliver an authentic and engaging experience for both novice drivers and seasoned pros. Set in a meticulously crafted open world, the game provides a comprehensive driving experience with a focus on realism, detail, and education.',
        description1: 'In Real Driving School, players step into the role of a learner driver navigating a variety of driving scenarios, ranging from city streets and highways to challenging off-road terrains. The game is designed to simulate real-life driving conditions, complete with dynamic weather effects, day-night cycles, and realistic traffic patterns. Players can choose from a wide array of vehicles, each with unique handling characteristics, from compact cars and sedans to SUVs and trucks.',
        description2: 'One of the standout features of Real Driving School is its detailed driving curriculum. The game offers a series of lessons and driving tests that cover essential skills such as parking, lane changing, merging, and obeying traffic signals. Each lesson is crafted to build upon the previous one, ensuring that players develop their driving skills progressively. The game also includes practical challenges and driving missions that test players abilities in real-world scenarios, such as navigating through congested traffic or driving in adverse weather conditions.',
        play: 'The game is graphics are highly realistic, with attention to detail in vehicle interiors, road textures, and environmental elements. The dynamic lighting and weather systems contribute to a more immersive experience, making each drive feel unique. The user interface is intuitive, with clear indicators and controls that mimic real-life vehicle systems. Additionally, Real Driving School features a realistic driving physics engine that accurately reflects how different vehicles respond to various driving inputs.',
        play1: 'Starting the Game: Upon launching Real Driving School, you wll be greeted with the main menu, where you can choose to start a new game or continue from a previous save. Select “New Game” to begin your driving journey. You’ll be prompted to create a profile, which will track your progress, achievements, and driving skills.',
        play2: 'Choosing Your Vehicle: The game features a range of vehicles, from small cars to large trucks. At the beginning, you might start with a basic vehicle. As you progress through lessons and complete missions, you’ll unlock more advanced and diverse vehicles. Choose a vehicle that you feel comfortable with, or experiment with different types to understand their handling characteristics. ',
        fileSize: 'Sep 6, 2024',
        version: '1.10.42',
        time: 'Aug 15, 2020',
        Appto: 'https://apps.apple.com/us/app/real-driving-school/id1499207656',
        Playto: 'https://play.google.com/store/apps/details?id=com.qizz.rds&hl=en-US'
    }, {
        img: '/Racing/AssolutoRacing.webp',
        title: 'Assoluto Racing',
        description: 'Assoluto Racing is a high-octane racing simulation game designed to deliver an exhilarating and authentic driving experience. Set against the backdrop of stunning, meticulously crafted environments, this game caters to racing enthusiasts who crave realism, precision, and a deep sense of immersion.',
        description1: 'In Assoluto Racing, players are thrust into the driver’s seat of a wide range of meticulously modeled cars, from sleek sports cars and powerful muscle cars to agile drift cars and high-end supercars. The game boasts a rich selection of vehicles, each accurately represented with detailed interiors and exteriors, and is equipped with realistic handling and performance characteristics.',
        description2: 'One of the game’s standout features is its impressive visual fidelity. The graphics are strikingly realistic, with high-definition textures, dynamic lighting, and intricate environmental details. Players will race through beautifully rendered tracks that span various real-world locations and unique settings, including city streets, mountain roads, and racetracks.',
        play: 'Getting Started: Launch Assoluto Racing from your device. Upon starting, you’ll be prompted to create a profile if you’re a new player. This profile will track your progress, stats, and achievements. After setting up your profile, you’ll enter the main menu, where you can choose between single-player and multiplayer modes, access settings, or view your garage. ',
        play1: 'Choosing a Vehicle: Begin by selecting your first vehicle. Assoluto Racing offers a range of cars with varying performance characteristics. If you’re new to the game, starting with a beginner-friendly car can help you get accustomed to the driving mechanics. As you progress, you’ll unlock and earn access to more advanced vehicles.',
        play2: 'Understanding the Controls: Familiarize yourself with the game’s controls. Assoluto Racing features realistic driving controls that include steering, accelerating, braking, and shifting gears. You can customize the control settings to your preference, whether using touch controls or a physical controller. Practice these controls in a practice mode or tutorial to get a feel for how the cars handle. ',
        fileSize: '1 GB',
        version: '2.16.4',
        time: 'Jul 16, 2024 ',
        Appto: 'https://apps.apple.com/us/app/assoluto-racing/id1055375459',
        Playto: 'https://play.google.com/store/apps/details?id=com.infinityvector.assolutoracing&hl=en-US'
    },


]