export const imgTile = [
    {
        img: '/Game/_Candy_Crush_Saga_2f0412.jpg',
        title: 'Candy Crush Saga',
        description: 'Candy Crush is a gemstone cube game developed by the British online game company King Digital. It has a synchronisation feature that allows progress to be switched between platforms. As of March 2013, Candy Crush has surpassed FarmVille 2 (Happy Farm) as the most popular game on Facebook, with 456 million monthly players This triple-play puzzle game is one of the most popular handheld games of all time, with more than a trillion total entries!',
        description1: 'Swipe and eliminate candies in this tasty puzzle adventure to take on the next level and feel the sweet joy of victory! Create colourful chains of elimination with quick thinking and clever moves to create delicious candy combinations and feel satisfied!Eliminate 3 or more candies in a row, or use your brain to use magic props to solve particularly difficult puzzles! Eliminate chocolate and collect sweet candies in thousands of levels that are guaranteed to leave you wanting more!Game features.',
        description2: 'Thousands of sweet levels and puzzles in the Candy Kingdom, with more levels added every 2 weeks to help you replenish your sugar levels!',
        play: 'Candy Saga is based on the theme of candy. The basic rule is to line up three to five identical candies in a line to eliminate candies to score points The game requires different candies to be grouped together and detonated, which will produce different effects of power. When a string of candies creates a combo, the player cannot move the other candies. The game is played one by one, allowing you to invite Facebook friends to unlock longer trips after every fifteen levels, with the first twenty levels being unlocked straight away and the thirty-fifth level requiring a ticket (sometimes a boat or airline ticket) in the Flash version.',
        play1: 'Each level has a different style and drops random sweets. Five hearts are provided at the start, with one deducted for each failed attempt and one replenished in 30 minutes, and you can ask your Facebook friends to return the hearts or pay for them.',
        play2: 'In the Flash version of the game, levels after Lemonade Lake (Episode 3) (including Lemonade Lake) are available for a fee and can be unlocked with the help of three Facebook friends, who can also share the levels with their friends. Of course, you can also use violence (Play quests) to get your hands on three keys to get a ticket (or a boat or airline ticket), but for each key you get, you have to wait a day before you can grab another one.',
        fileSize: '77.7MB',
        version: '1.235.1.1',
        time: 'October 15, 2013',
        Appto: 'https://apps.apple.com/us/app/candy-crush-saga/id553834731',
        Playto: 'https://play.google.com/store/apps/details?id=com.king.candycrushsaga&hl=None',
        screenShot:['/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga1.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga2.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga3.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga4.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga5.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga6.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga7.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga8.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga9.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga10.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga11.webp','/Game/GameScreenshot/Candy_Crush_Saga/Candy_Crush_Saga12.webp']
    },
    {
        img: '/Game/Acrylic_Nails!_02fe03.jpg',
        title: 'Acrylic Nails!',
        description: 'Acrylic Nails! is a casual game for all girls. In this game, you will become a nail artist!',
        description1: 'I believe that every girl has a love of beauty, from the way she dresses, to her hair and even to the delicacy of her fingers. Maybe you want to try doing your own nail art now? Come and experience what it is like to be a nail artist in Acrylic Nails!Here you will have a variety of colours of nail polish, as well as a variety of sequins, diamonds and other embellishments - which match would you like to try? It is all up to you. In this super free game environment, use your own ideas and creativity to leave your creations on each nail',
        description2: 'Don it forget that this is a real simulation game and that the nail artists in the game will be the same as those in real life. First you have to complete the preparation work such as trimming your nails and getting rid of dead skin, then you choose the colour you want and paint your nails with the effect you want. Not good enough for you? Then use the painting tools now to create your favourite pattern on your fingertips. Of course, the game fully respects each player is choice, so you can create any style of nail art you want.',
        play: 'Acrylic Nails! is an extremely simple and free game, perfect for passing the time in your spare time. The simple gameplay makes Acrylic Nails! suitable for girls of all ages, there are no goals and the only fun is that each player can create their own nail art!There are various nail art tools to use to polish your fingertips into the shape you want, then choose one of the various red, yellow, blue, green, green, blue and purple colours you like and paint it on your nails. You can stop there and make a simple style or embellish it to make this nail art even more exciting.',
        play1: 'Perhaps you could also draw a pattern yourself and add it to the nail to create a unique nail art.Design each fingertip differently and at the end you can see your results on display. Each elaborate creation is hard to come by, but each one will give you a great surprise.',
        play2: 'The gameplay is as simple as that, and because of that Acrylic Nails! is able to offer more gameplay opportunities for every player, allowing more players to experience nail art in the game and even help you learn a little about it.',
        fileSize: '99M',
        version: '1.0.2',
        time: '26 july 2021',
        Appto: 'https://apps.apple.com/us/app/acrylic-nails/id1526638009',
        Playto: 'https://play.google.com/store/apps/details?id=com.crazylabs.acrylic.nails&hl=None',
        screenShot:['/Game/GameScreenshot/Acrylic_Nails/AcrylicNails1.webp','/Game/GameScreenshot/Acrylic_Nails/AcrylicNails2.webp','/Game/GameScreenshot/Acrylic_Nails/AcrylicNails3.webp','/Game/GameScreenshot/Acrylic_Nails/AcrylicNails4.webp','/Game/GameScreenshot/Acrylic_Nails/AcrylicNails5.webp','/Game/GameScreenshot/Acrylic_Nails/AcrylicNails6.webp','/Game/GameScreenshot/Acrylic_Nails/AcrylicNails7.webp','/Game/GameScreenshot/Acrylic_Nails/AcrylicNails8.webp','/Game/GameScreenshot/Acrylic_Nails/AcrylicNails9.webp']
    },
    {
        img: '/Game/Age_of_Z_Origins_Tower_Defense_ff8008.jpg',
        title: 'Age of Z Origins:Tower Defense',
        description: 'Form alliances with other like-minded commanders around the world, destroy your opponents and seize capitals, and you will become the leader of the world and lead the renaissance of humanity!',
        description1: 'Destroy the zombies, form alliances, and manage city-states in an apocalyptic world to rebuild human civilisation in a zombie strategy MMO!The zombie crisis has broken out and swept the world, pushing thousands of years of human civilization to the brink of total destruction. At this moment, you carry the hope for the revival of humanity.',
        description2: 'With the souls of steel armies, guns and chariots, you will be able to survive.By dismantling the tide of corpses and crushing the enemy to recover lost territories.Rebuild cities and save refugees to bring about the reawakening of civilisation.',
        play: '1. Recruit troops, develop technology and destroy the enemy!The weak are the strong and armaments are survival: you need to make more machine guns and ammunition, fill your chariots with fuel and weld sharp blades, and research high-tech soldiers earlier.',
        play1: '2. The wisdom of men is short, the wisdom of men is long: to run a city-state, to develop a military, to command a war, you will be very busy if you are alone, so you may need to recruit a sexy international spy, a mad scientist, a brave sheriff, no, you may need more talents!',
        play2: '3. Normal zombies are one man is enemy, mutated zombies are ten thousand: Witnesses have seen human-sized zombies as big as hills or zombie bears, and I fear there are even more terrifying beings whose existence is unknown to us because they have killed all the witnesses. These spokesmen of doom await your challenge!',
        fileSize: '50M',
        version: '1.2.87',
        time: '6 August 2021',
        Appto: 'https://apps.apple.com/us/app/age-of-origins-tower-defense/id1376515087',
        Playto: 'https://play.google.com/store/apps/details?id=com.camelgames.aoz&hl=None',
        screenShot:['/Game/GameScreenshot/Tower_Defense/TowerDefense1.webp','/Game/GameScreenshot/Tower_Defense/TowerDefense2.webp','/Game/GameScreenshot/Tower_Defense/TowerDefense3.webp','/Game/GameScreenshot/Tower_Defense/TowerDefense4.webp']
    },
    {
        img: '/Game/Angry_Birds_2_7e630c.jpg',
        title: 'Angry Birds 2',
        description1: 'New to Angry Birds? Iconic characters, hilarious experiences, and fun to play, come to Angry Birds 2. The fun gaming experience, happy leisure time, has captured the hearts of millions of players.',
        description2: 'Older players of Angry Birds? The classic Angry Birds game, everything you love, is still there and adds exciting elements. Choose which birds to pop up, have fun with your friends, grab multi-stage levels, and compete and cooperate with players from around the world.Features.',
        description: 'New to Angry Birds? Iconic characters, hilarious experiences, and fun to play, come to Angry Birds 2. The fun gaming experience, happy leisure time, has captured the hearts of millions of players.',
        play: 'Selectable birds. Choose which bird to put on the slingshot and use strategy to defeat the pigs!Multi-stage levels. Have fun with exciting multi-stage levels, but watch out for Boss Piggy!Daily Challenges. Only have a few moments to spare? Then come to the daily challenge and get in and out quickly for some rewards.',
        play: 'In the game, players need to control a flock of birds and help them retrieve the eggs stolen by a group of green piglets. In each level, the pigs are protected by buildings made of wood, ice and stone (sometimes even cushioned by balls of leather), and the goal is to destroy all the pigs in the level. The goal is to destroy all the piglets in the level by using a slingshot to launch the birds and hit the piglets directly, or indirectly by hitting the buildings to make them collapse and overwhelm them. In many levels, additional props are provided in the scenes, such as boxes with explosives or rocks, which can be used in conjunction with the bird is impact to defeat pigs in hard-to-reach positions.',
        play1: 'There are 11 different types of birds to use in the game. In the earliest levels, only the most basic red birds are available.',
        play2: 'However, as the game progresses, more types of birds will be available, some of which can be used to perform special abilities by tapping the touch screen while flying through the air. For example, the blue bird (smallest, good at smashing ice) will split into three slightly smaller birds, the yellow bird (good at drilling wood) can accelerate the sprint, the black bird (bulky, good at destroying rocks) will explode, the white bird will drop an explodable egg and fly away at high speed up to the right, etc., and the green bird will pirouette. Piglets also come in a variety of sizes, with smaller pigs being relatively more fragile',
        fileSize: '320.1MB',
        version: '3.4.0',
        time: 'June 08, 2021',
        Appto: 'https://apps.apple.com/us/app/angry-birds-2/id880047117',
        Playto: 'https://play.google.com/store/apps/details?id=com.rovio.baba&hl=None',
        screenShot:['/Game/GameScreenshot/Angry_Birds2/AngryBirds1.webp','/Game/GameScreenshot/Angry_Birds2/AngryBirds2.webp','/Game/GameScreenshot/Angry_Birds2/AngryBirds3.webp','/Game/GameScreenshot/Angry_Birds2/AngryBirds4.webp','/Game/GameScreenshot/Angry_Birds2/AngryBirds5.webp','/Game/GameScreenshot/Angry_Birds2/AngryBirds6.webp','/Game/GameScreenshot/Angry_Birds2/AngryBirds7.webp']
    },
    {
        img: '/Game/Angry_Birds_Match_3_b5cfa3.jpg',
        title: 'Angry Birds Match 3',
        description: 'Explore the world and collect cubs in this adorable three-puzzle game!',
        description1: 'Decorate the scene, win new costumes and dress up the cubs to express your style!Pass the levels to help rescue the chicks from the pigs and raise your cute flock of chicks - they are waiting for you at ......Features.',
        description2: 'Unique and fun triple elimination game with challenging puzzles Collect cute chicks to nurture and unlock new worlds for them to explore Match 4 or more items to bring out the big birds - Red, Bomb and Chuck! Entertain your flock by finding new items to decorate the scene Participate in special themed events throughout the year!.',
        play: 'In Angry Birds Match3, as the levels are completed, several scenes such as Surprise Party, Gourmand Time and Dreamy Delicious will be unlocked in turn, while baby birds with different appearances will be invited to enter the scenes, and you can change their appearance by spending a little gold coins. Of course, if you want more little ones to join, pay to open boxes to get new characters quickly.',
        play1: 'elimination gameplay and given special skills.The "L" and "T" type elimination occurs when Red appears, it can run in a certain direction so as to eliminate a whole row; and "the main show" bomb black Bomb, with the previous weight, strong impact force, strong wave of the bird set, when the five consecutive elimination occurs, can eliminate a certain direction of three rows or three columns at the same time.When the skills of the angry bird cross, a chain reaction will occur, and when used at the right time not only can eliminate the target object, but also save steps.',
        play2: 'Green pigs, wooden boxes, TNT explosives and other elements that players are very familiar with are all present in the game.',
        fileSize: '135M',
        version: '5.4.0',
        time: 'October 11, 2021',
        Appto: 'https://apps.apple.com/us/app/angry-birds-2/id880047117',
        Playto: 'https://play.google.com/store/apps/details?id=com.rovio.abmatch3&hl=en&gl=us',
        screenShot:['/Game/GameScreenshot/AngryBirdsMatc_3/AngryBirdsMatch1.webp','/Game/GameScreenshot/AngryBirdsMatc_3/AngryBirdsMatch2.webp','/Game/GameScreenshot/AngryBirdsMatc_3/AngryBirdsMatch3.webp','/Game/GameScreenshot/AngryBirdsMatc_3/AngryBirdsMatch4.webp','/Game/GameScreenshot/AngryBirdsMatc_3/AngryBirdsMatch5.webp','/Game/GameScreenshot/AngryBirdsMatc_3/AngryBirdsMatch6.webp','/Game/GameScreenshot/AngryBirdsMatc_3/AngryBirdsMatch7.webp','/Game/GameScreenshot/AngryBirdsMatc_3/AngryBirdsMatch8.webp']
    },
    {
        img: '/Game/Bloons_TD_6_b13a64.jpg',
        title: 'Bloons TD 6',
        description: 'Bloons TD 6 (BTD6) is a popular tower defense game developed and published by Ninja Kiwi. The game is available on multiple platforms, including PC, mobile, and console. The game has gained a massive following due to its unique gameplay, stunning graphics, and challenging levels.',
        description1: 'The objective of BTD6 is to stop balloons (known as "bloons") from reaching the end of a path by placing towers that attack them. As players progress through levels, they earn money that can be used to purchase more towers or upgrade existing ones. The game features a wide range of towers, each with unique abilities and upgrade paths, as well as various types of bloons, each with different strengths and weaknesses.',
        description2: 'One of the most notable aspects of BTD6 is its playability. The game is easy to learn, but challenging to master. The early levels are straightforward, but as players progress, the difficulty ramps up significantly, requiring careful strategy and precise placement of towers to succeed. The game also offers a range of difficulty options, allowing players to adjust the challenge to their liking.',
        play: '1.Understand the Basics: The objective of the game is to stop the bloons from reaching the end of the path by placing towers that attack them. You start with a limited amount of money, which you can use to buy and upgrade towers. Each tower has its own strengths and weaknesses, so it is important to choose the right tower for the job.',
        play1: '2.Start with Easy Levels: The early levels of the game are designed to be relatively easy, so they are a great place to start. As you progress, the difficulty increases, so take your time and build up your skills before moving on to more challenging levels.',
        play2: '3.Choose Your Towers Wisely: There are many different types of towers to choose from, each with its own strengths and weaknesses. Some towers are better suited for certain types of bloons, while others are more effective against specific bloon types. It is important to experiment with different towers to find the best strategy for each level.',
        fileSize: 'April 4, 2023',
        version: 'PC',
        time: 'April 4, 2023',
        Appto: 'https://apps.apple.com/us/app/bloons-td-6/id1118115766',
        Playto: 'https://play.google.com/store/apps/details?id=com.ninjakiwi.bloonstd6&hl=en_US',
        screenShot:['/Game/GameScreenshot/BloonsTD/BloonsTD1.webp','/Game/GameScreenshot/BloonsTD/BloonsTD2.webp','/Game/GameScreenshot/BloonsTD/BloonsTD3.webp','/Game/GameScreenshot/BloonsTD/BloonsTD4.webp','/Game/GameScreenshot/BloonsTD/BloonsTD5.webp','/Game/GameScreenshot/BloonsTD/BloonsTD6.webp','/Game/GameScreenshot/BloonsTD/BloonsTD7.webp','/Game/GameScreenshot/BloonsTD/BloonsTD8.webp']
    },
    {
        img: '/Game/Bowmasters_665dd7.jpg',
        title: 'Bowmasters',
        description: 'Bowmasters is a sizzling aim and shoot game that has a wealth of content for you:.',
        description1: ' - 41 crazy characters from every dimension, absolutely free! 41 different weapons to use to cause havoc, using the ragdoll physics system to inflict amazing casualties!Fight epic duels with your best friends. Grab your mates and show them what you are got!',
        description2: 'Multiple game modes. Shoot down birds or fruit, beat your enemies in duels and earn money doing it!',
        play: 'Bowmasters is a cartoon-style archery game with a variety of oddly drawn characters and all the necessary elements of a bow and arrow game.',
        play1: 'The game is very simple to play, with the player only having to tap the screen to adjust their character. The game is very easy to play, as the player only needs to tap the screen to adjust the angle and strength of the character is shot, and to shoot the bow and arrow according to the enemy is position before striking. The game requires a certain number of victories in the basic mutual shooting mode to unlock more game play such as duck hunting and apple shooting.',
        play2: 'Countless rewards for your skills!',
        fileSize: '691.1 MB',
        version: '2.15.5',
        time: 'Jun 1, 2021',
        Appto: 'https://apps.apple.com/us/app/bowmasters-multiplayer-game/id1118431695',
        Playto: 'about:blank',
        screenShot:['/Game/GameScreenshot/Bowmasters/Bowmaster1.webp','/Game/GameScreenshot/Bowmasters/Bowmaster2.webp','/Game/GameScreenshot/Bowmasters/Bowmaster3.webp','/Game/GameScreenshot/Bowmasters/Bowmaster4.webp','/Game/GameScreenshot/Bowmasters/Bowmaster5.webp','/Game/GameScreenshot/Bowmasters/Bowmaster6.webp','/Game/GameScreenshot/Bowmasters/Bowmaster7.webp','/Game/GameScreenshot/Bowmasters/Bowmaster8.webp']
    },
]
